# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eY26Nv-rf7DR7-jLD5bNWfOWnfCeXQYu
"""

# Criação da lista com os numeros do cartão
num = list(input("Digite o numero do Cartão (sem espaços): ")) 
 
# Transformando a lista em inteiro
intnum= list(map(int, num))

# Criando listas Antes do "For", para guardar as multiplicações e adições
ladc = [] # lista adição
lmult = [] # lista multiplicação

# Reverter a lista de inteiros "intnum" 
for i in list(reversed(intnum)) [1::2]:
  mult = i * 2 # Multiplicando os numeros pulando 1
  lmult.append(mult)
  

# Adicionando valores separados a cima em uma lista 
for s in lmult:
  if s > 9 : 
    adc = s - 9
    ladc.append(adc)
  else :
    ladc.append(s)

# Adicionando valores restantes em uma lista final 
for f in list(reversed(intnum)) [::2] :
  ladc.append(f)

#somar a lista toda
sum(ladc)
print(sum(ladc))

#Mostrando Validade e qual a bandeira do cartão
if sum(ladc) % 10 == 0 :
  if intnum[0] == 4:
    print("VISA")
  elif intnum[0] == 3 and (intnum[1] == 4 or 7):
    print("AMEX")
  elif intnum[0] == 5 and (intnum[1] == 1 or 2 or 3 or 4 or 5):
    print("MASTERCARD")
else:
  print("INVALIDO")